# based on https://jacobian.org/til/github-actions-poetry/
on:
  push:
    branches: [master]
  pull_request:

name: check

jobs:
  check:
    strategy:
      matrix:
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - run: uv run --frozen ./ci/check.sh
